### ISSUE TITLE
Report relying on OS specific variable

### ISSUE THREAD

**Issue by wiresecurity** [theonaunheim/pyfair#13]
Base report relies on an OS specific variable USERNAME that may not be present on other OSs.
metadata = pd.Series({
            'Author': os.environ['USERNAME'],

Suggest to perform a validation of the environment variable first.

**Comment by theonaunheim** [comment]
Good call out. Thanks.

Using [getpass.getuser()](https://docs.python.org/3/library/getpass.html#getpass.getuser) should remedy this. Giving this a shot and will update.

**Comment by theonaunheim** [comment]
@wiresecurity 
I believe this has been fixed in version 0.1-alpha.6. Would you please confirm this is fixed on your end?

**Comment by wiresecurity** [comment]
looks good to me :) thanks!
