### ISSUE TITLE
Contact Details

### ISSUE THREAD

**Issue by data-88** [theonaunheim/pyfair#16]
Hi Theo, 

We are a cybersecurity consultancy based in Johannesburg, South Africa. 

We wanted to chat to you about potentially using your tool as part of our consultancy services. 

Is there an email address that we can contact you on?

Thanks so much, 

Andrew
andrew1on1@gmail.com

**Comment by theonaunheim** [comment]
Certainly. Please feel free to email me at theonaunheim@gmail.com.
