### ISSUE TITLE
Add docker image

### ISSUE THREAD

**Issue by theonaunheim** [theonaunheim/pyfair#22]
Because why not?

**Comment by priamai** [comment]
Ahaha I can help you with that, do you want it embedded in a jupyter notebook?
I basically already have it.

**Comment by theonaunheim** [comment]
Hey, @priamai . I appreciate the offer, but I think was the universe's way of telling me to get off my butt and learn how to create a minimally functional Docker Hub image. Any critiques are definitely welcomed, though.

Dockerfile here: `https://github.com/theonaunheim/pyfair/blob/dev/Dockerfile`
Docker Hub here: `https://hub.docker.com/repository/docker/theonaunheim/pyfair-notebook`

**Comment by priamai** [comment]
Docker is working great.
