### ISSUE TITLE
Set another Currency

### ISSUE THREAD

**Issue by charles-dubos** [theonaunheim/pyfair#24]
Hi,

Thanks for your work, the result for FAIR analyses is really impressive!
However, it would be great to be able to change the currency in the reports (for example € instead of $).

**Comment by theonaunheim** [comment]
Hello, @charles-dubos .

Thanks for the feedback. A couple of people have brought this oversight to my attention, so this will be included in the next release (0.2-beta.0). 

When creating a FairSimpleReport you will be allowed to supply a keyword argument called "currency_prefix". This will allow you to substitute a currency symbol of your choice in the report.

My best guess at this point is roughly 45 days out, but I beleive this change is already active in the "dev" branch should you want to try it out.

**Comment by charles-dubos** [comment]
Great! It works (only curves have still '$' currencies, but it works perfectly on the tables of the report!)

**Comment by theonaunheim** [comment]
Thanks for the bug report ... this will allow me to get a putative fix in prior to beta.

**Comment by theonaunheim** [comment]
@charles-dubos ,

Version 0.2-beta.0 was delayed so I put this into version 0.1-alpha.11 instead. Would you please download the newest version of this package from PyPI, ensure the fix is accurate, and then close this issue at your convenience?

Thank you again for the bug report--much appreciated.
