### ISSUE TITLE
Code example with all node specified

### ISSUE THREAD

**Issue by priamai** [theonaunheim/pyfair#32]
Hi there,
would be nice to have a full code example with all the nodes until the child level of the model tree.
Cheers.

**Comment by theonaunheim** [comment]
Thanks for the suggestion. Definite yes.

Are you coming from at this from a "what are the legal values for each input node" angle?

If so, this should be a good fit for the "Why are my parameters throwing errors" FAQ.

**Comment by priamai** [comment]
Yes it would be a nice addition to that.

**Comment by theonaunheim** [comment]
Hey, @priamai . This has been added to the development documentation for dev and will eventually move to master.

https://pyfair.readthedocs.io/en/dev/#functioning-example-with-all-nodes-and-input-types
